CREATE TABLE circuit_facts (
    circuit_key INTEGER UNIQUE,
    circuit_short_name TEXT PRIMARY KEY,
    canonical_name TEXT NOT NULL,
    track_length_km TEXT NOT NULL,
    race_distance_km TEXT NOT NULL,
    laps INTEGER NOT NULL,
    turns INTEGER NOT NULL,
    first_grand_prix INTEGER NOT NULL,
    direction TEXT NOT NULL,
    drs_zones INTEGER NOT NULL,
    lap_record TEXT NOT NULL,
    lap_record_holder TEXT NOT NULL,
    lap_record_year INTEGER NOT NULL,
    overtaking_hotspot TEXT NOT NULL,
    quick_fact TEXT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO circuit_facts (circuit_short_name, canonical_name, track_length_km, race_distance_km, laps, turns, first_grand_prix, direction, drs_zones, lap_record, lap_record_holder, lap_record_year, overtaking_hotspot, quick_fact) VALUES
('Bahrain', 'Bahrain International Circuit', '5.412', '308.238', 57, 15, 2004, 'Clockwise', 3, '1:31.447', 'Pedro de la Rosa', 2005, 'Turn 1 braking zone after the main straight.', 'A desert track with heavy traction demands and large temperature swings after sunset.'),
('Jeddah', 'Jeddah Corniche Circuit', '6.174', '308.450', 50, 27, 2021, 'Anti-clockwise', 3, '1:30.734', 'Lewis Hamilton', 2021, 'Final corner and Turn 1 sequence with slipstream effect.', 'One of the fastest street circuits on the calendar, built around long full-throttle sweeps.'),
('Melbourne', 'Albert Park Circuit', '5.278', '306.124', 58, 14, 1996, 'Clockwise', 4, '1:19.813', 'Charles Leclerc', 2024, 'Turn 3 after the high-speed opening sector.', 'A semi-street layout where track evolution is usually dramatic across the weekend.'),
('Baku', 'Baku City Circuit', '6.003', '306.049', 51, 20, 2016, 'Anti-clockwise', 2, '1:43.009', 'Charles Leclerc', 2019, 'Turn 1 after the very long pit straight.', 'Combines one of the slowest castle sections in F1 with one of the longest straights.'),
('Miami', 'Miami International Autodrome', '5.412', '308.326', 57, 19, 2022, 'Clockwise', 3, '1:29.708', 'Max Verstappen', 2023, 'Turn 11 at the end of the back straight.', 'A stadium-based street-style layout with strong traction zones and heavy braking events.'),
('Imola', 'Autodromo Enzo e Dino Ferrari', '4.909', '309.049', 63, 19, 1980, 'Anti-clockwise', 1, '1:15.484', 'Lewis Hamilton', 2020, 'Tamburello into Villeneuve when exits are strong.', 'A classic old-school circuit where kerb management and rhythm matter more than pure drag efficiency.'),
('Monaco', 'Circuit de Monaco', '3.337', '260.286', 78, 19, 1950, 'Clockwise', 1, '1:12.909', 'Lewis Hamilton', 2021, 'Pit strategy matters more than on-track passing here.', 'The narrowest and slowest average-speed venue in F1, where qualifying often defines the weekend.'),
('Montréal', 'Circuit Gilles Villeneuve', '4.361', '305.270', 70, 14, 1978, 'Clockwise', 3, '1:13.078', 'Valtteri Bottas', 2019, 'Final chicane and Turn 1 at the end of the pit straight.', 'A stop-start track defined by traction, brake stability, and aggressive kerb usage.'),
('Barcelona', 'Circuit de Barcelona-Catalunya', '4.657', '307.236', 66, 14, 1991, 'Clockwise', 2, '1:16.330', 'Max Verstappen', 2023, 'Turn 1 after the front straight with tow assistance.', 'Long a benchmark test track because it exposes both aerodynamic balance and tyre wear.'),
('Spielberg', 'Red Bull Ring', '4.318', '306.452', 71, 10, 1970, 'Clockwise', 3, '1:05.619', 'Carlos Sainz', 2020, 'Turns 3 and 4 after uphill braking zones.', 'A very short lap where tiny setup changes can move the car noticeably up or down the grid.'),
('Silverstone', 'Silverstone Circuit', '5.891', '306.198', 52, 18, 1950, 'Clockwise', 2, '1:27.097', 'Max Verstappen', 2020, 'Brooklands and Stowe after strong aero sectors.', 'High-speed direction changes through Maggotts-Becketts-Chapel are among the toughest in motorsport.'),
('Budapest', 'Hungaroring', '4.381', '306.630', 70, 14, 1986, 'Clockwise', 2, '1:16.627', 'Lewis Hamilton', 2020, 'Turn 1 under braking after the main straight.', 'Often described as Monaco without barriers because clean air and track position are critical.'),
('Spa-Francorchamps', 'Circuit de Spa-Francorchamps', '7.004', '308.052', 44, 19, 1950, 'Clockwise', 2, '1:46.286', 'Valtteri Bottas', 2018, 'Kemmel straight after Eau Rouge-Raidillon exit speed.', 'The longest circuit on the calendar with huge weather variation across different sectors.'),
('Zandvoort', 'Circuit Zandvoort', '4.259', '306.587', 72, 14, 1952, 'Clockwise', 2, '1:11.097', 'Lewis Hamilton', 2021, 'Turn 1 if the banking and exit are well managed.', 'Known for dramatic banking and lateral load, making tyre stress a major setup theme.'),
('Monza', 'Autodromo Nazionale Monza', '5.793', '306.720', 53, 11, 1950, 'Clockwise', 2, '1:21.046', 'Rubens Barrichello', 2004, 'Turn 1 Rettifilo and the Variante della Roggia.', 'The classic low-drag temple of speed where straight-line efficiency dominates setup priorities.'),
('Marina Bay', 'Marina Bay Street Circuit', '4.928', '306.143', 62, 19, 2008, 'Anti-clockwise', 4, '1:34.486', 'Daniel Ricciardo', 2024, 'Turn 14 and the final sector braking zones after DRS assistance.', 'A humid night race that regularly becomes one of the most physically demanding events of the year.'),
('Suzuka', 'Suzuka Circuit', '5.807', '307.471', 53, 18, 1987, 'Clockwise', 1, '1:30.983', 'Lewis Hamilton', 2019, 'Chicane on the run to the final line if exits are strong.', 'The only figure-eight layout in F1, blending iconic flowing sectors with high commitment corners.'),
('Lusail', 'Lusail International Circuit', '5.419', '308.611', 57, 16, 2021, 'Clockwise', 1, '1:24.319', 'Max Verstappen', 2023, 'Turn 1 after the pit straight braking zone.', 'A fast, flowing venue where lateral tyre load and sustained cornering energy are critical.'),
('Austin', 'Circuit of the Americas', '5.513', '308.405', 56, 20, 2012, 'Anti-clockwise', 2, '1:36.169', 'Charles Leclerc', 2019, 'Turn 12 after the long back straight descent.', 'Its opening esses echo Silverstone and Suzuka while the hairpins reward traction and braking stability.'),
('Mexico City', 'Autodromo Hermanos Rodriguez', '4.304', '305.354', 71, 17, 1963, 'Clockwise', 3, '1:17.774', 'Valtteri Bottas', 2021, 'Turn 1 after the very long start-finish straight at altitude.', 'High altitude cuts drag and downforce at the same time, making cooling and braking especially tricky.'),
('São Paulo', 'Autodromo Jose Carlos Pace', '4.309', '305.879', 71, 15, 1973, 'Anti-clockwise', 2, '1:10.540', 'Valtteri Bottas', 2018, 'Turn 1 Senna S with slipstream support from the uphill final sector.', 'A short anti-clockwise lap with elevation change, mixed grip phases, and frequent weather swings.'),
('Las Vegas', 'Las Vegas Strip Circuit', '6.201', '309.958', 50, 17, 2023, 'Clockwise', 2, '1:35.490', 'Lando Norris', 2024, 'Turn 14 after the flat-out Strip section.', 'Cold night conditions and long straights make tyre warm-up and braking confidence central themes.'),
('Yas Marina', 'Yas Marina Circuit', '5.281', '306.183', 58, 16, 2009, 'Anti-clockwise', 2, '1:26.103', 'Max Verstappen', 2021, 'Turns 6 and 9 after the long DRS runs.', 'The modern Yas Marina layout improved flow and passing by removing the old hotel chicane complex.'),
('Shanghai', 'Shanghai International Circuit', '5.451', '305.066', 56, 16, 2004, 'Clockwise', 2, '1:32.238', 'Michael Schumacher', 2004, 'The huge Turn 14 stop after the back straight.', 'Features one of the longest-radius opening corners in F1, which punishes front tyre abuse immediately.');
